mysql:
    host: "127.0.0.1:3306"

#    Create A user like this:
#      CREATE USER canal IDENTIFIED BY 'Your Password';
#      GRANT SELECT, SHOW VIEW, Reload, REPLICATION SLAVE, REPLICATION CLIENT ON *.* TO 'canal'@'%';
#      FLUSH PRIVILEGES;

    username: "canal"
    password: "Your Password"
    timezone: Asia/Shanghai
    server_id: 10001 # the server id of mysql slave
    charset: utf8
    flavor: mysql # mysql, mariadb

targets:
  redis:
    addrs: ["127.0.0.1:6379"]
    password: ""

task:
  task_mode: incremental
  max_wait: 100ms  # Maximum waiting time between 2 jobs
  max_bulk_size: 1000 # Maximum events size for 1 job
  script_dir: "scripts"

  binlog:
    file: mysql-bin.000001
    position: 0

  rules:
    - schema: test_db
      table: test_table
      call: "Consumer"
      args:
